USE acs; 

CREATE TABLE ARTICLE 
(ID int(12) NOT NULL AUTO_INCREMENT,
TYPE varchar(255),
INTITULE varchar(255),
DESCRIPTION varchar(255),
QUANTITE int(4),
DESTINATAIRE varchar(255),
CONSTRAINT ARTICLEPK PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE USER
(ID int(12) NOT NULL AUTO_INCREMENT,
USERNAME varchar(50) UNIQUE,
EMAIL varchar(50) UNIQUE,
PASSWORD varchar(100),
CONSTRAINT USERPK PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE ROLE
(ID int(12) NOT NULL AUTO_INCREMENT,
NAME varchar(60),
CONSTRAINT USERPK PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE USER_ROLE
(USER_ID int(12) NOT NULL,
ROLE_ID int(12) NOT NULL,
CONSTRAINT USERROLEPK PRIMARY KEY (USER_ID,ROLE_ID),
CONSTRAINT USERROLEUSERFK FOREIGN KEY (USER_ID) REFERENCES USER(ID),
CONSTRAINT USERROLEROLEFK FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;


CREATE TABLE RESERVATION
(ID int(12) NOT NULL AUTO_INCREMENT,
QUANTITE int(4),
DATE_EMPRUNT DATETIME,
DATE_RESTITUTION DATETIME,
CREER_LE DATETIME,
CREER_PAR varchar(255),
VALIDE_LE DATETIME,
VALIDE_PAR varchar(255),
CLIENT_ID int(10),
ASSO tinyint(1) DEFAULT 0,
NOM varchar(45),
PRENOM varchar(45),
ACTIVE varchar(10),
COMMENTAIRE varchar(20000)
CONSTRAINT RESERVATIONPK PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;


CREATE TABLE CLIENT
(ID int(10) NOT NULL AUTO_INCREMENT,
TYPE varchar(255),
NOM varchar(255),
ADRESSE varchar(400),
PHONE varchar(255),
CONSTRAINT CLIENTPK PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;


CREATE TABLE RESERVATION_ARTICLE
(ID_RESERVATION int(12) NOT NULL,
ID_ARTICLE int(12) NOT NULL,
QUANTITE int(4)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

ALTER TABLE RESERVATION_ARTICLE ADD CONSTRAINT RESARTICLEPK PRIMARY KEY (ID_RESERVATION,ID_ARTICLE);
ALTER TABLE RESERVATION_ARTICLE ADD CONSTRAINT RESARTRESFK FOREIGN KEY (ID_RESERVATION) REFERENCES RESERVATION(ID);
ALTER TABLE RESERVATION_ARTICLE ADD CONSTRAINT RESARTARTFK FOREIGN KEY (ID_ARTICLE) REFERENCES ARTICLE(ID);
